[build]
functions = "functions"

[build.environment]
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  TERM = "xterm"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
package = "netlify-plugin-cypress"
  [plugins.inputs]
#  enable = false
  configFile = "cypress.netlify.json"
  #  record = true
  #  browser = "electron"
    [plugins.inputs.preBuild]
    #    enable = false
    enable = true
    spa = true
    start = 'npx prisma generate && npx netlify dev'
    wait-on = 'http://localhost:8888'

[functions]
external_node_modules = ["express"]
